AFRICAST = {"109":{"department":"AFRICAST","number":"109","title":"Running While Others Walk: African Perspectives on Development (AFRICAST 209)","min_units":5,"max_units":5,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[true,false,false,false,false],"start_time":"15:15:00","end_time":"18:05:00"}],"gers":""},
"190":{"department":"AFRICAST","number":"190","title":"Madagascar Prefield Seminar","min_units":1,"max_units":2,"autumn_classes":[],"winter_classes":[{"days":[false,false,false,false,true],"start_time":"12:15:00","end_time":"13:05:00"}],"spring_classes":[],"gers":""},
"235":{"department":"AFRICAST","number":"235","title":"Designing Research-Based Interventions to Solve Global Health Problems (AFRICAST 135, EDUC 135X, EDUC 335X, MED 235)","min_units":3,"max_units":4,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[false,true,false,true,false],"start_time":"16:00:00","end_time":"17:15:00"}],"gers":""},
"141A":{"department":"AFRICAST","number":"141A","title":"Science, Technology, and Medicine in Africa (ANTHRO 141A)","min_units":4,"max_units":4,"autumn_classes":[{"days":[true,false,true,false,false],"start_time":"10:00:00","end_time":"11:50:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"212":{"department":"AFRICAST","number":"212","title":"AIDS, Literacy, and Land: Foreign Aid and Development in Africa (AFRICAST 112)","min_units":5,"max_units":5,"autumn_classes":[],"winter_classes":[{"days":[true,false,false,false,false],"start_time":"15:15:00","end_time":"18:05:00"}],"spring_classes":[],"gers":""},
"135":{"department":"AFRICAST","number":"135","title":"Designing Research-Based Interventions to Solve Global Health Problems (AFRICAST 235, EDUC 135X, EDUC 335X, MED 235)","min_units":3,"max_units":4,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[false,true,false,true,false],"start_time":"16:00:00","end_time":"17:15:00"}],"gers":""},
"209":{"department":"AFRICAST","number":"209","title":"Running While Others Walk: African Perspectives on Development (AFRICAST 109)","min_units":5,"max_units":5,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[true,false,false,false,false],"start_time":"15:15:00","end_time":"18:05:00"}],"gers":""},
"112":{"department":"AFRICAST","number":"112","title":"AIDS, Literacy, and Land: Foreign Aid and Development in Africa (AFRICAST 212)","min_units":5,"max_units":5,"autumn_classes":[],"winter_classes":[{"days":[true,false,false,false,false],"start_time":"15:15:00","end_time":"18:05:00"}],"spring_classes":[],"gers":"GER:ECGlobalCom"},
"200":{"department":"AFRICAST","number":"200","title":"The HIV/AIDS Epidemic in Tanzania: A Pre-Field Seminar","min_units":1,"max_units":1,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[false,true,false,false,false],"start_time":"20:30:00","end_time":"22:20:00"}],"gers":""}
}