{"120":{"department":"CHILATST","number":"120","title":"Queer Raza (FEMGEN 120, ILAC 287)","min_units":3,"max_units":5,"autumn_classes":[{"days":[true,false,false,false,false],"start_time":"13:15:00","end_time":"16:05:00"}],"winter_classes":[],"spring_classes":[],"gers":"WAY-AII, WAY-ED"},
"179F":{"department":"CHILATST","number":"179F","title":"Flor y Canto: Poetry Workshop (CSRE 179F, TAPS 179F, TAPS 279F)","min_units":3,"max_units":5,"autumn_classes":[],"winter_classes":[{"days":[false,false,false,true,false],"start_time":"14:15:00","end_time":"17:05:00"}],"spring_classes":[],"gers":"WAY-CE"},
"200":{"department":"CHILATST","number":"200","title":"Latin@ Literature (CSRE 200, ILAC 280, ILAC 382)","min_units":3,"max_units":5,"autumn_classes":[{"days":[false,false,true,false,false],"start_time":"14:15:00","end_time":"17:05:00"}],"winter_classes":[],"spring_classes":[],"gers":"GER:DB-Hum, WAY-AII, WAY-ED"},
"14N":{"department":"CHILATST","number":"14N","title":"Growing Up Bilingual (CSRE 14N, EDUC 114N)","min_units":3,"max_units":3,"autumn_classes":[],"winter_classes":[{"days":[false,true,false,true,false],"start_time":"10:00:00","end_time":"11:50:00"}],"spring_classes":[],"gers":"WAY-ED, WAY-SI"},
"53J":{"department":"CHILATST","number":"53J","title":"Love Notes: Queers of Color on Politics of the Heart (CSRE 53J)","min_units":3,"max_units":3,"autumn_classes":[{"days":[false,false,false,false,true],"start_time":"09:00:00","end_time":"10:50:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"183X":{"department":"CHILATST","number":"183X","title":"Practicum in English-Spanish School & Community Interpreting (EDUC 183X, EDUC 283X)","min_units":3,"max_units":4,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[false,true,false,false,false],"start_time":"14:15:00","end_time":"17:05:00"}],"gers":""},
"180E":{"department":"CHILATST","number":"180E","title":"Introduction to Chicana/o-Latina/o Studies (CSRE 180E)","min_units":5,"max_units":5,"autumn_classes":[{"days":[true,false,true,false,false],"start_time":"11:00:00","end_time":"12:15:00"}],"winter_classes":[],"spring_classes":[],"gers":"GER:DB-Hum, GER:EC-AmerCul"},
"168":{"department":"CHILATST","number":"168","title":"New Citizenship: Grassroots Movements for Social Justice in the U.S. (ANTHRO 169A, CSRE 168, FEMGEN 140H)","min_units":5,"max_units":5,"autumn_classes":[],"winter_classes":[{"days":[false,false,false,false,true],"start_time":"10:00:00","end_time":"12:50:00"}],"spring_classes":[],"gers":""},
"198":{"department":"CHILATST","number":"198","title":"Internship for Public Service (CSRE 198)","min_units":1,"max_units":5,"autumn_classes":[],"winter_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"spring_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"gers":""}
}