ENVRES = {"240":{"department":"ENVRES","number":"240","title":"Environmental Decision-Making and Risk Perception","min_units":1,"max_units":1,"autumn_classes":[],"winter_classes":[{"days":[false,true,false,false,false],"start_time":"14:15:00","end_time":"15:05:00"}],"spring_classes":[],"gers":""},
"280":{"department":"ENVRES","number":"280","title":"Introduction to Environmental Science","min_units":3,"max_units":3,"autumn_classes":[{"days":[false,true,false,true,false],"start_time":"15:15:00","end_time":"16:45:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"277C":{"department":"ENVRES","number":"277C","title":"Specialized Writing and Reporting: Environmental Journalism (COMM 177C, COMM 277C, EARTHSYS 177C)","min_units":4,"max_units":5,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[true,false,true,false,false],"start_time":"10:00:00","end_time":"11:50:00"}],"gers":""},
"225":{"department":"ENVRES","number":"225","title":"E-IPER Current Topics Seminar","min_units":1,"max_units":1,"autumn_classes":[{"days":[false,false,false,true,false],"start_time":"12:15:00","end_time":"13:05:00"}],"winter_classes":[{"days":[false,false,false,true,false],"start_time":"12:15:00","end_time":"13:05:00"}],"spring_classes":[{"days":[false,false,false,true,false],"start_time":"12:15:00","end_time":"13:05:00"}],"gers":""},
"200":{"department":"ENVRES","number":"200","title":"Sustaining Action: Research, Analysis and Writing for the Public (EARTHSYS 200)","min_units":3,"max_units":3,"autumn_classes":[{"days":[true,false,true,false,false],"start_time":"13:15:00","end_time":"14:45:00"}],"winter_classes":[],"spring_classes":[{"days":[true,false,true,false,false],"start_time":"13:15:00","end_time":"14:45:00"}],"gers":""},
"250":{"department":"ENVRES","number":"250","title":"Environmental Governance (CEE 277C)","min_units":3,"max_units":3,"autumn_classes":[],"winter_classes":[{"days":[false,false,true,false,false],"start_time":"15:15:00","end_time":"18:05:00"}],"spring_classes":[],"gers":""},
"270":{"department":"ENVRES","number":"270","title":"Graduate Practicum in Environment and Resources","min_units":1,"max_units":9,"autumn_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"winter_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"spring_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"gers":""},
"230":{"department":"ENVRES","number":"230","title":"Field Survey Data Collection & Analysis","min_units":3,"max_units":3,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"gers":""},
"290":{"department":"ENVRES","number":"290","title":"Capstone Project Seminar in Environment and Resources","min_units":1,"max_units":3,"autumn_classes":[{"days":[false,true,false,false,false],"start_time":"13:15:00","end_time":"15:05:00"}],"winter_classes":[],"spring_classes":[{"days":[false,true,false,false,false],"start_time":"13:15:00","end_time":"15:05:00"}],"gers":""}
}