{"2":{"department":"ESF","number":"2","title":"Education as Self-Fashioning: The German Tradition of Bildung or How to Become a Global Citizen","min_units":7,"max_units":7,"autumn_classes":[{"days":[false,false,false,true,false],"start_time":"11:30:00","end_time":"12:45:00"},{"days":[false,true,false,true,false],"start_time":"09:00:00","end_time":"10:50:00"},{"days":[true,false,true,false,false],"start_time":"11:00:00","end_time":"12:50:00"}],"winter_classes":[],"spring_classes":[],"gers":"Writing 1"},
"4A":{"department":"ESF","number":"4A","title":"Education as Self-Fashioning: Learning to Change","min_units":7,"max_units":7,"autumn_classes":[{"days":[true,false,true,false,false],"start_time":"09:00:00","end_time":"10:50:00"},{"days":[false,true,false,true,false],"start_time":"11:00:00","end_time":"12:50:00"},{"days":[false,false,false,true,false],"start_time":"09:00:00","end_time":"10:15:00"}],"winter_classes":[],"spring_classes":[],"gers":"Writing 1"},
"2A":{"department":"ESF","number":"2A","title":"Education as Self-Fashioning: The German Tradition of Bildung or How to Become a Global Citizen","min_units":7,"max_units":7,"autumn_classes":[{"days":[false,true,false,true,false],"start_time":"09:00:00","end_time":"10:50:00"},{"days":[false,false,false,true,false],"start_time":"13:15:00","end_time":"14:30:00"},{"days":[true,false,true,false,false],"start_time":"11:00:00","end_time":"12:50:00"}],"winter_classes":[],"spring_classes":[],"gers":"Writing 1"},
"1A":{"department":"ESF","number":"1A","title":"Education as Self-Fashioning: The Active, Inquiring, Beautiful Life","min_units":7,"max_units":7,"autumn_classes":[{"days":[false,false,true,false,false],"start_time":"16:15:00","end_time":"17:30:00"},{"days":[false,true,false,true,false],"start_time":"15:15:00","end_time":"17:05:00"},{"days":[false,true,false,true,false],"start_time":"11:00:00","end_time":"12:50:00"}],"winter_classes":[],"spring_classes":[],"gers":"Writing 1"},
"3A":{"department":"ESF","number":"3A","title":"Education as Self-Fashioning: How to be a Public Intellectual","min_units":7,"max_units":7,"autumn_classes":[{"days":[false,true,false,true,false],"start_time":"11:00:00","end_time":"12:50:00"},{"days":[false,true,false,true,false],"start_time":"09:00:00","end_time":"10:50:00"},{"days":[false,false,true,false,false],"start_time":"13:15:00","end_time":"14:30:00"}],"winter_classes":[],"spring_classes":[],"gers":"Writing 1"},
"50":{"department":"ESF","number":"50","title":"Education as Self-Fashioning Lecture Series","min_units":1,"max_units":1,"autumn_classes":[{"days":[false,false,false,false,true],"start_time":"12:00:00","end_time":"13:30:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"6A":{"department":"ESF","number":"6A","title":"Education as Self-Fashioning: The Wind of Freedom","min_units":7,"max_units":7,"autumn_classes":[{"days":[false,true,false,true,false],"start_time":"11:00:00","end_time":"12:50:00"},{"days":[true,false,false,false,false],"start_time":"13:15:00","end_time":"14:30:00"},{"days":[false,true,false,true,false],"start_time":"15:15:00","end_time":"17:05:00"}],"winter_classes":[],"spring_classes":[],"gers":"Writing 1"},
"4":{"department":"ESF","number":"4","title":"Education as Self-Fashioning: Learning to Change","min_units":7,"max_units":7,"autumn_classes":[{"days":[false,true,false,false,false],"start_time":"09:00:00","end_time":"10:15:00"},{"days":[false,true,false,true,false],"start_time":"11:00:00","end_time":"12:50:00"},{"days":[true,false,true,false,false],"start_time":"09:00:00","end_time":"10:50:00"}],"winter_classes":[],"spring_classes":[],"gers":"Writing 1"},
"6":{"department":"ESF","number":"6","title":"Education as Self-Fashioning: The Wind of Freedom","min_units":7,"max_units":7,"autumn_classes":[{"days":[false,true,false,true,false],"start_time":"11:00:00","end_time":"12:50:00"},{"days":[true,false,false,false,false],"start_time":"11:00:00","end_time":"12:15:00"},{"days":[false,true,false,true,false],"start_time":"15:15:00","end_time":"17:05:00"}],"winter_classes":[],"spring_classes":[],"gers":"Writing 1"},
"1":{"department":"ESF","number":"1","title":"Education as Self-Fashioning: The Active, Inquiring, Beautiful Life","min_units":7,"max_units":7,"autumn_classes":[{"days":[false,true,false,true,false],"start_time":"11:00:00","end_time":"12:50:00"},{"days":[false,true,false,true,false],"start_time":"15:15:00","end_time":"17:05:00"},{"days":[false,false,true,false,false],"start_time":"14:15:00","end_time":"15:30:00"}],"winter_classes":[],"spring_classes":[],"gers":"Writing 1"},
"3":{"department":"ESF","number":"3","title":"Education as Self-Fashioning: How to be a Public Intellectual","min_units":7,"max_units":7,"autumn_classes":[{"days":[false,true,false,true,false],"start_time":"09:00:00","end_time":"10:50:00"},{"days":[false,false,true,false,false],"start_time":"11:00:00","end_time":"12:15:00"},{"days":[false,true,false,true,false],"start_time":"11:00:00","end_time":"12:50:00"}],"winter_classes":[],"spring_classes":[],"gers":"Writing 1"},
"5A":{"department":"ESF","number":"5A","title":"Education as Self-Fashioning: Thinking Like a Philosopher","min_units":7,"max_units":7,"autumn_classes":[{"days":[true,false,true,false,false],"start_time":"11:00:00","end_time":"12:50:00"},{"days":[false,true,false,true,false],"start_time":"16:15:00","end_time":"18:05:00"},{"days":[false,false,false,true,false],"start_time":"14:15:00","end_time":"15:30:00"}],"winter_classes":[],"spring_classes":[],"gers":"Writing 1"},
"5":{"department":"ESF","number":"5","title":"Education as Self-Fashioning: Thinking Like a Philosopher","min_units":7,"max_units":7,"autumn_classes":[{"days":[false,true,false,true,false],"start_time":"16:15:00","end_time":"18:05:00"},{"days":[true,false,true,false,false],"start_time":"11:00:00","end_time":"12:50:00"},{"days":[false,true,false,false,false],"start_time":"14:15:00","end_time":"15:30:00"}],"winter_classes":[],"spring_classes":[],"gers":"Writing 1"}
}