{"110":{"department":"FILMSTUD","number":"110","title":"Science Fiction Cinema (FILMSTUD 310)","min_units":4,"max_units":4,"autumn_classes":[{"days":[false,false,true,false,false],"start_time":"19:00:00","end_time":"21:00:00"}],"winter_classes":[],"spring_classes":[],"gers":"GER:DB-Hum, WAY-AII"},
"290":{"department":"FILMSTUD","number":"290","title":"Movies and Methods-The Judy Garland Seminar (FILMSTUD 490)","min_units":5,"max_units":5,"autumn_classes":[],"winter_classes":[{"days":[true,false,false,false,false],"start_time":"14:15:00","end_time":"17:05:00"}],"spring_classes":[],"gers":""},
"4":{"department":"FILMSTUD","number":"4","title":"Introduction to Film Study","min_units":5,"max_units":5,"autumn_classes":[],"winter_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"},{"days":[false,false,false,true,false],"start_time":"11:00:00","end_time":"12:00:00"},{"days":[false,false,true,false,false],"start_time":"17:00:00","end_time":"18:00:00"},{"days":[true,false,false,false,false],"start_time":"19:00:00","end_time":"21:30:00"}],"spring_classes":[],"gers":"GER:DB-Hum, WAY-AII"},
"100B":{"department":"FILMSTUD","number":"100B","title":"History of World Cinema II, 1930-1959 (FILMSTUD 300B)","min_units":4,"max_units":4,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[true,false,false,false,false],"start_time":"19:00:00","end_time":"21:00:00"}],"gers":"GER:DB-Hum, WAY-AII"},
"157":{"department":"FILMSTUD","number":"157","title":"Film Noir from Bogart to Mulholland Drive (FILMSTUD 357)","min_units":4,"max_units":4,"autumn_classes":[],"winter_classes":[{"days":[true,false,true,false,false],"start_time":"11:00:00","end_time":"12:30:00"}],"spring_classes":[],"gers":""},
"145B":{"department":"FILMSTUD","number":"145B","title":"History and Politics in Russian and Eastern European Cinema (FILMSTUD 345B, REES 301A)","min_units":4,"max_units":5,"autumn_classes":[{"days":[false,false,true,false,false],"start_time":"14:15:00","end_time":"17:05:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"100C":{"department":"FILMSTUD","number":"100C","title":"History of World Cinema III, 1960-Present (FILMSTUD 300C)","min_units":4,"max_units":4,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[false,true,false,true,false],"start_time":"14:15:00","end_time":"15:30:00"}],"gers":"GER:DB-Hum, WAY-AII"},
"102":{"department":"FILMSTUD","number":"102","title":"Theories of the Moving Image (FILMSTUD 302)","min_units":4,"max_units":4,"autumn_classes":[],"winter_classes":[{"days":[true,false,true,false,false],"start_time":"15:15:00","end_time":"16:15:00"}],"spring_classes":[],"gers":"GER:DB-Hum, WAY-AII"},
"115":{"department":"FILMSTUD","number":"115","title":"Documentary Issues and Traditions (FILMSTUD 315)","min_units":4,"max_units":4,"autumn_classes":[{"days":[false,true,false,false,false],"start_time":"19:00:00","end_time":"21:00:00"}],"winter_classes":[],"spring_classes":[],"gers":"GER:DB-SocSci, WAY-AII"},
"101":{"department":"FILMSTUD","number":"101","title":"Fundamentals of Cinematic Analysis (FILMSTUD 301)","min_units":4,"max_units":4,"autumn_classes":[{"days":[false,false,true,false,false],"start_time":"19:00:00","end_time":"21:30:00"},{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"winter_classes":[],"spring_classes":[],"gers":"GER:DB-Hum, WAY-AII"},
"100A":{"department":"FILMSTUD","number":"100A","title":"History of World Cinema I, 1895-1929 (FILMSTUD 300A)","min_units":4,"max_units":4,"autumn_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"},{"days":[false,true,false,true,false],"start_time":"15:15:00","end_time":"16:30:00"}],"winter_classes":[],"spring_classes":[],"gers":"GER:DB-Hum, WAY-AII"},
"110N":{"department":"FILMSTUD","number":"110N","title":"Darkness in Light: The Filmic Imagination of Horror","min_units":3,"max_units":3,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[false,true,false,false,false],"start_time":"19:00:00","end_time":"21:00:00"}],"gers":"WAY-AII"},
"165A":{"department":"FILMSTUD","number":"165A","title":"Fashion Shows: From Lady Godiva to Lady Gaga (ARTHIST 165A, ARTHIST 365A, FILMSTUD 365A)","min_units":4,"max_units":4,"autumn_classes":[],"winter_classes":[{"days":[false,true,false,true,false],"start_time":"14:15:00","end_time":"15:45:00"}],"spring_classes":[],"gers":"GER:DB-Hum"}
}