{"215":{"department":"MI","number":"215","title":"Principles of Biological Technologies (IMMUNOL 215)","min_units":3,"max_units":3,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[false,true,false,true,false],"start_time":"14:15:00","end_time":"16:05:00"}],"gers":""},
"245":{"department":"MI","number":"245","title":"Computational Modeling of Microbial Communities (BIOE 115)","min_units":4,"max_units":4,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[true,false,true,false,false],"start_time":"13:15:00","end_time":"15:05:00"}],"gers":""},
"210":{"department":"MI","number":"210","title":"Advanced Pathogenesis of Bacteria, Viruses, and Eukaryotic Parasites","min_units":4,"max_units":4,"autumn_classes":[],"winter_classes":[{"days":[true,false,true,false,false],"start_time":"15:15:00","end_time":"17:05:00"}],"spring_classes":[],"gers":""},
"70Q":{"department":"MI","number":"70Q","title":"Photographing Nature","min_units":3,"max_units":3,"autumn_classes":[{"days":[true,false,true,false,false],"start_time":"14:15:00","end_time":"16:05:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"250":{"department":"MI","number":"250","title":"Frontiers in Microbiology and Immunology","min_units":1,"max_units":1,"autumn_classes":[{"days":[false,true,false,false,false],"start_time":"17:30:00","end_time":"18:20:00"}],"winter_classes":[{"days":[false,true,false,false,false],"start_time":"17:30:00","end_time":"18:20:00"}],"spring_classes":[{"days":[false,true,false,false,false],"start_time":"17:30:00","end_time":"18:20:00"}],"gers":""},
"204":{"department":"MI","number":"204","title":"Innate Immunology (IMMUNOL 204, MI 104)","min_units":3,"max_units":3,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[false,false,true,false,false],"start_time":"11:00:00","end_time":"12:30:00"}],"gers":""},
"120":{"department":"MI","number":"120","title":"Bacteria in Health and Disease (BIO 120)","min_units":3,"max_units":3,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[false,true,false,true,false],"start_time":"14:15:00","end_time":"16:00:00"}],"gers":""},
"104":{"department":"MI","number":"104","title":"Innate Immunology (IMMUNOL 204, MI 204)","min_units":3,"max_units":3,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[true,false,true,false,false],"start_time":"11:00:00","end_time":"12:30:00"}],"gers":""},
"211":{"department":"MI","number":"211","title":"Advanced Immunology I (IMMUNOL 201)","min_units":3,"max_units":3,"autumn_classes":[],"winter_classes":[{"days":[true,false,true,false,false],"start_time":"13:15:00","end_time":"14:45:00"}],"spring_classes":[],"gers":""},
"185":{"department":"MI","number":"185","title":"Topics in Microbiology (MI 285)","min_units":3,"max_units":3,"autumn_classes":[],"winter_classes":[{"days":[true,false,true,false,true],"start_time":"10:00:00","end_time":"10:50:00"}],"spring_classes":[],"gers":""}
}