OSPMOSC = {"51M":{"department":"OSPMOSC","number":"51M","title":"Second-Year Russian","min_units":5,"max_units":5,"autumn_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"44":{"department":"OSPMOSC","number":"44","title":"Economic Reform and Economic Policy in Modern Russia","min_units":5,"max_units":5,"autumn_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"10M":{"department":"OSPMOSC","number":"10M","title":"Intensive First-Year Russian","min_units":8,"max_units":8,"autumn_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"45":{"department":"OSPMOSC","number":"45","title":"Russia in the Changing World","min_units":5,"max_units":5,"autumn_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"177M":{"department":"OSPMOSC","number":"177M","title":"Fourth-Year Russian","min_units":5,"max_units":5,"autumn_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"68":{"department":"OSPMOSC","number":"68","title":"From Science to Market: Technical Innovation Policy in Post-Soviet Russia","min_units":5,"max_units":5,"autumn_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"winter_classes":[],"spring_classes":[],"gers":"GER:DBEngrAppSci"},
"111M":{"department":"OSPMOSC","number":"111M","title":"Third-Year Russian","min_units":5,"max_units":5,"autumn_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"46":{"department":"OSPMOSC","number":"46","title":"Cultural Diversity in Contemporary World: Normative, Political, and Socio-Anthropological Dimensions","min_units":5,"max_units":5,"autumn_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"72":{"department":"OSPMOSC","number":"72","title":"Space, Politics, and Modernity in Russia","min_units":5,"max_units":5,"autumn_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"winter_classes":[],"spring_classes":[],"gers":"GER:DBSocSci, GER:ECGlobalCom"}
}