PORTLANG = {"12A":{"department":"PORTLANG","number":"12A","title":"Accelerated Second-Year Portuguese, Part 2","min_units":4,"max_units":5,"autumn_classes":[{"days":[true,false,true,false,true],"start_time":"13:15:00","end_time":"14:45:00"}],"winter_classes":[{"days":[true,false,true,false,true],"start_time":"11:00:00","end_time":"12:30:00"}],"spring_classes":[{"days":[true,false,true,false,true],"start_time":"13:15:00","end_time":"14:45:00"}],"gers":""},
"1F":{"department":"PORTLANG","number":"1F","title":"Accelerated First-Year Business Portuguese, Part I: Focus on Business and Economics.","min_units":4,"max_units":5,"autumn_classes":[{"days":[true,true,true,true,true],"start_time":"08:00:00","end_time":"08:50:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"163":{"department":"PORTLANG","number":"163","title":"Contemporary Issues in the Lusophone World. Fourth-Year Portuguese","min_units":3,"max_units":5,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"gers":""},
"161":{"department":"PORTLANG","number":"161","title":"Advanced Reading in Portuguese, Fourth-year Portuguese","min_units":3,"max_units":5,"autumn_classes":[{"days":[true,false,true,false,true],"start_time":"12:15:00","end_time":"13:05:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"162":{"department":"PORTLANG","number":"162","title":"Advanced Writing in Portuguese, Fourth-year Portuguese","min_units":3,"max_units":5,"autumn_classes":[],"winter_classes":[{"days":[true,false,true,false,true],"start_time":"12:15:00","end_time":"13:05:00"}],"spring_classes":[],"gers":""},
"2F":{"department":"PORTLANG","number":"2F","title":"Accelerated First-Year Business Portuguese, Part 2: Focus on Business and Economics.","min_units":4,"max_units":5,"autumn_classes":[],"winter_classes":[{"days":[true,true,true,true,true],"start_time":"08:00:00","end_time":"08:50:00"}],"spring_classes":[],"gers":""},
"102":{"department":"PORTLANG","number":"102","title":"Brazil in Text: Advanced Grammar and Composition","min_units":3,"max_units":5,"autumn_classes":[],"winter_classes":[{"days":[true,false,true,false,true],"start_time":"12:15:00","end_time":"13:05:00"}],"spring_classes":[],"gers":""},
"11A":{"department":"PORTLANG","number":"11A","title":"Accelerated Second-Year Portuguese, Part 1","min_units":4,"max_units":5,"autumn_classes":[{"days":[true,false,true,false,true],"start_time":"11:00:00","end_time":"12:30:00"}],"winter_classes":[{"days":[true,false,true,false,true],"start_time":"11:00:00","end_time":"12:30:00"}],"spring_classes":[{"days":[true,false,true,false,true],"start_time":"13:15:00","end_time":"14:45:00"},{"days":[true,false,true,false,true],"start_time":"11:00:00","end_time":"12:30:00"}],"gers":""},
"2A":{"department":"PORTLANG","number":"2A","title":"Accelerated First-Year Portuguese, Part 2","min_units":4,"max_units":5,"autumn_classes":[{"days":[true,true,true,true,true],"start_time":"13:15:00","end_time":"14:05:00"}],"winter_classes":[{"days":[true,true,true,true,true],"start_time":"13:15:00","end_time":"14:05:00"},{"days":[true,true,true,true,true],"start_time":"10:00:00","end_time":"10:50:00"}],"spring_classes":[{"days":[true,true,true,true,true],"start_time":"13:15:00","end_time":"14:05:00"},{"days":[true,true,true,true,true],"start_time":"11:00:00","end_time":"11:50:00"}],"gers":""},
"1A":{"department":"PORTLANG","number":"1A","title":"Accelerated First-Year Portuguese, Part 1","min_units":4,"max_units":5,"autumn_classes":[{"days":[true,true,true,true,true],"start_time":"13:15:00","end_time":"14:05:00"},{"days":[true,true,true,true,true],"start_time":"10:00:00","end_time":"10:50:00"},{"days":[true,true,true,true,true],"start_time":"11:00:00","end_time":"11:50:00"}],"winter_classes":[{"days":[true,true,true,true,true],"start_time":"14:15:00","end_time":"15:05:00"},{"days":[true,true,true,true,true],"start_time":"10:00:00","end_time":"10:50:00"},{"days":[true,true,true,true,true],"start_time":"13:15:00","end_time":"14:05:00"}],"spring_classes":[{"days":[true,true,true,true,true],"start_time":"11:00:00","end_time":"11:50:00"},{"days":[true,true,true,true,true],"start_time":"09:00:00","end_time":"09:50:00"}],"gers":""},
"103":{"department":"PORTLANG","number":"103","title":"Advanced Conversation: Brazil Today","min_units":3,"max_units":5,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[true,false,true,false,true],"start_time":"12:15:00","end_time":"13:05:00"}],"gers":""},
"193Q":{"department":"PORTLANG","number":"193Q","title":"Spaces and Voices of Brazil through Film (ILAC 193Q)","min_units":3,"max_units":4,"autumn_classes":[{"days":[false,true,false,true,false],"start_time":"15:15:00","end_time":"17:05:00"}],"winter_classes":[],"spring_classes":[],"gers":"GER:DBHum, GER:ECGlobalCom"},
"101":{"department":"PORTLANG","number":"101","title":"Reading Brazil","min_units":3,"max_units":5,"autumn_classes":[{"days":[true,false,true,false,true],"start_time":"12:15:00","end_time":"13:05:00"}],"winter_classes":[],"spring_classes":[],"gers":""}
}