{"227":{"department":"RAD","number":"227","title":"Functional MRI Methods (BIOPHYS 227)","min_units":3,"max_units":3,"autumn_classes":[],"winter_classes":[{"days":[false,true,false,true,false],"start_time":"13:30:00","end_time":"15:30:00"}],"spring_classes":[],"gers":""},
"225":{"department":"RAD","number":"225","title":"Ultrasound Imaging and Therapeutic Applications (BIOE 325)","min_units":3,"max_units":3,"autumn_classes":[{"days":[true,false,true,false,false],"start_time":"13:15:00","end_time":"15:05:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"222B":{"department":"RAD","number":"222B","title":"Multimodality Molecular Imaging in Living Subjects II (BIOE 222B)","min_units":4,"max_units":4,"autumn_classes":[],"winter_classes":[{"days":[true,false,false,false,true],"start_time":"09:00:00","end_time":"10:50:00"}],"spring_classes":[],"gers":""},
"260":{"department":"RAD","number":"260","title":"Computational Methods for Biomedical Image Analysis and Interpretation (BIOMEDIN 260)","min_units":3,"max_units":4,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[true,false,true,false,false],"start_time":"12:50:00","end_time":"14:05:00"}],"gers":""},
"222A":{"department":"RAD","number":"222A","title":"Multimodality Molecular Imaging in Living Subjects I (BIOE 222A)","min_units":4,"max_units":4,"autumn_classes":[{"days":[true,false,false,false,true],"start_time":"09:00:00","end_time":"10:50:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"223":{"department":"RAD","number":"223","title":"Physics and Engineering of X-Ray Computed Tomography (BIOE 223)","min_units":3,"max_units":3,"autumn_classes":[{"days":[true,false,true,false,true],"start_time":"15:15:00","end_time":"16:05:00"}],"winter_classes":[],"spring_classes":[],"gers":""},
"226":{"department":"RAD","number":"226","title":"In Vivo Magnetic Resonance Spectroscopy and Imaging (BIOE 226)","min_units":3,"max_units":3,"autumn_classes":[],"winter_classes":[{"days":[false,true,false,true,false],"start_time":"09:30:00","end_time":"11:00:00"}],"spring_classes":[],"gers":""},
"222C":{"department":"RAD","number":"222C","title":"Multimodality Molecular Imaging in Living Subjects III (BIOE 222C)","min_units":4,"max_units":4,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[true,false,false,false,true],"start_time":"09:00:00","end_time":"10:50:00"}],"gers":""},
"226":{"department":"RAD","number":"226","title":"In Vivo Magnetic Resonance Spectroscopy and Imaging","min_units":3,"max_units":3,"autumn_classes":[],"winter_classes":[{"days":[false,true,false,true,false],"start_time":"09:30:00","end_time":"11:00:00"}],"spring_classes":[],"gers":""},
"228":{"department":"RAD","number":"228","title":"Magnetic Resonance Imaging Programming Topics","min_units":3,"max_units":3,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[false,true,false,true,false],"start_time":"15:45:00","end_time":"16:45:00"}],"gers":""}
}