{"200E":{"department":"STS","number":"200E","title":"Technology, Nature, and Environmentalism","min_units":5,"max_units":5,"autumn_classes":[],"winter_classes":[],"spring_classes":[{"days":[true,false,true,false,false],"start_time":"11:00:00","end_time":"12:30:00"}],"gers":"WAY-AII, WAY-SI"},
"131":{"department":"STS","number":"131","title":"Science Technology & Environmental Justice","min_units":5,"max_units":5,"autumn_classes":[],"winter_classes":[{"days":[false,true,false,true,false],"start_time":"14:15:00","end_time":"15:45:00"}],"spring_classes":[],"gers":"WAY-SI"},
"160Q":{"department":"STS","number":"160Q","title":"Technology in Contemporary Society","min_units":4,"max_units":4,"autumn_classes":[{"days":[false,false,true,false,false],"start_time":"14:15:00","end_time":"16:30:00"}],"winter_classes":[],"spring_classes":[],"gers":"GER:DB-SocSci, WAY-SI"},
"200A":{"department":"STS","number":"200A","title":"Food and Society: Politics, Culture and Technology","min_units":5,"max_units":5,"autumn_classes":[{"days":[true,false,true,false,false],"start_time":"11:00:00","end_time":"12:30:00"},{"days":[false,false,false,true,false],"start_time":"11:00:00","end_time":"11:50:00"},{"days":[false,false,true,false,false],"start_time":"16:15:00","end_time":"17:05:00"}],"winter_classes":[],"spring_classes":[],"gers":"WAY-ED, WAY-SI"},
"1":{"department":"STS","number":"1","title":"The Public Life of Science and Technology","min_units":5,"max_units":5,"autumn_classes":[],"winter_classes":[{"days":[false,false,false,true,false],"start_time":"16:15:00","end_time":"17:05:00"},{"days":[false,false,false,true,false],"start_time":"11:00:00","end_time":"11:50:00"},{"days":[false,false,false,false,true],"start_time":"12:15:00","end_time":"13:05:00"},{"days":[false,false,false,true,false],"start_time":"15:15:00","end_time":"16:05:00"},{"days":[false,false,false,true,false],"start_time":"18:15:00","end_time":"19:05:00"},{"days":[false,false,false,false,true],"start_time":"10:00:00","end_time":"10:50:00"},{"days":[false,false,false,false,true],"start_time":"11:00:00","end_time":"11:50:00"},{"days":[false,false,false,true,false],"start_time":"15:15:00","end_time":"16:05:00"},{"days":[true,false,true,false,false],"start_time":"11:00:00","end_time":"12:15:00"},{"days":[false,false,false,true,false],"start_time":"18:15:00","end_time":"19:05:00"},{"days":[false,false,false,true,false],"start_time":"16:15:00","end_time":"17:05:00"}],"spring_classes":[],"gers":"GER:DB-SocSci, WAY-AII, WAY-SI"},
"140":{"department":"STS","number":"140","title":"Science, Technology and Politics","min_units":4,"max_units":4,"autumn_classes":[],"winter_classes":[{"days":[false,true,false,true,false],"start_time":"11:00:00","end_time":"12:30:00"}],"spring_classes":[],"gers":"WAY-SI"},
"200F":{"department":"STS","number":"200F","title":"Sociology of Innovation and Invention","min_units":5,"max_units":5,"autumn_classes":[],"winter_classes":[{"days":[false,true,false,true,false],"start_time":"14:15:00","end_time":"15:45:00"}],"spring_classes":[],"gers":""},
"199J":{"department":"STS","number":"199J","title":"Editing a Science Technology and Society Journal","min_units":1,"max_units":2,"autumn_classes":[],"winter_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"spring_classes":[{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"gers":""},
"200D":{"department":"STS","number":"200D","title":"Text Technologies: A History (ENGLISH 184H)","min_units":5,"max_units":5,"autumn_classes":[{"days":[false,true,false,true,false],"start_time":"14:15:00","end_time":"15:45:00"},{"days":[false,false,false,false,false],"start_time":"00:00:00","end_time":"00:00:00"}],"winter_classes":[],"spring_classes":[],"gers":"GER:DB-Hum, WAY-AII"},
"200B":{"department":"STS","number":"200B","title":"Global Mobilities (ANTHRO 146)","min_units":5,"max_units":5,"autumn_classes":[],"winter_classes":[{"days":[true,false,true,false,false],"start_time":"12:35:00","end_time":"14:05:00"}],"spring_classes":[],"gers":""}
}